# Generated by Django 5.0.6 on 2024-06-25 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationPointTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetUsersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user', models.CharField(max_length=255, unique=True)),
                ('target_pos', models.CharField(blank=True, max_length=255, null=True)),
                ('target_pho', models.CharField(blank=True, max_length=255, null=True)),
                ('current_location', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminUsersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Stopped', 'Stopped'), ('Traveling', 'Traveling'), ('Started', 'Started'), ('Reached', 'Reached')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking_app.destinationpointtable')),
                ('target_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking_app.targetuserstable')),
            ],
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('admin_user_table_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking_app.adminuserstable')),
                ('destination_point_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking_app.destinationpointtable')),
                ('target_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking_app.targetuserstable')),
            ],
        ),
    ]
